name: color_picker_example
description: Two examples of how to use the FlexColorPicker package.
version: 2.2.0
publish_to: 'none'
environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  # https://pub.dev/packages/flex_color_picker
  flex_color_picker: ^2.2.0

  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^1.0.3

  # https://pub.dev/packages/google_fonts
  google_fonts: ^2.3.1

  # https://pub.dev/packages/hive
  hive: ^2.0.5

  # https://pub.dev/packages/path_provider:
  path_provider: ^2.0.9

  # https://pub.dev/packages/url_launcher
  # Used for launching a WEB URL (by Google flutter.dev).
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:

flutter:
  uses-material-design: true
  # All image assets used by the program.
  # Only an app icon used in the About dialog.
  assets:
    - assets/images/