name: color_picker_example
description: Two examples of how to use the FlexColorPicker package.
version: 3.1.0
publish_to: 'none'
environment:
  sdk: '>=2.19.0-0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  # https://pub.dev/packages/flex_color_picker
  flex_color_picker:
    path: ../

  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.1.3

  # https://pub.dev/packages/google_fonts
  google_fonts: ^4.0.1

  # https://pub.dev/packages/hive
  hive: ^2.2.3

  # https://pub.dev/packages/path_provider:
  path_provider: ^2.0.12

  # https://pub.dev/packages/url_launcher
  # Used for launching a WEB URL (by Google flutter.dev).
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:

flutter:
  uses-material-design: true
  # All image assets used by the program.
  # Only an app icon used in the About dialog.
  assets:
    - assets/images/