name: flex_color_picker
description: A customizable Flutter primary, accent and custom color picker. Includes an optional HSV wheel color picker.
version: 2.6.0-dev.1
homepage: https://github.com/rydmike/flex_color_picker

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.1.0-0.0.pre.2111'

dependencies:
  flutter:
    sdk: flutter

  # Color utilities by Google (material.io).
  # Used to compute and create Tonal Palette theme colors.
  # Flutter SDK from 2.10.0 stable also uses and depends on this package.
  # Use ^0.1.3 because Flutter stable 2.10.x uses it.
  # Use ^0.1.4 because Flutter stable 3.0.x uses it.
  # Latest release is 0.2.0, that master 3.1.0-x uses after 5.8.2022.
  # material_color_utilities: ^0.1.3
  # material_color_utilities: ^0.1.4
  material_color_utilities: ^0.2.0

dev_dependencies:
  collection:
  flutter_test:
    sdk: flutter
  test:

flutter:
  uses-material-design: true
  assets:
    - assets/
